language: swift
osx_image: xcode12.2
install:
  - bundle install
script:
  - fastlane tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - gem install jazzy
  - make documentation
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: docs
  on:
    branch: master
